### ISSUE TITLE
Support more filters (API)

### ISSUE THREAD

**Issue by moul** [berty/yolo#126]
* [x] artifact_kinds=...
* [x] build_id=...
* [x] build_driver=...
* [x] project_id=...
* [x] mergerequest_author_id=...
* [x] artifact_id=...
* [x] mergerequest_state=...
* [x] build_state=...
* [x] mergerequest_id=...
* [x] with_artifacts=1
* [x] with_mergerequest=1
* [ ] artifact_driver=...
* [ ] branch_name=...
* [ ] artifact_state=...
* [ ] job_name=
* [ ] merged VS PR VS other
* [ ] job_id=

also support the `<none>` or `<other>` for enums

**Comment by ekelen** [comment]
Is there a reason `?artifact_id=xyz` returns the entire build + all of its artifacts? (e.g. `curl -u $AUTH "https://yolo.berty.io/api/build-list?artifact_id=buildkite_86a373f48077362ead7782285262b86f" | jq`

**Comment by moul** [comment]
yep, build-list returns builds, and except for the "filter the artifact kinds" which is clearly an "I dont care about other types", filtering by artifact ID, can just be that you know an artifact and want to see the other ones for that build

if you don't want it from the front, feel free to filter it from the front :)

**Comment by ekelen** [comment]
Filtering by project would be cool, because right now if you have this combination selected, you will also see Chat builds.

![image](https://user-images.githubusercontent.com/24300177/82210959-4dae0c80-9910-11ea-9d6f-60330938f6a1.png)

**Comment by moul** [comment]
> Filtering by project would be cool, because right now if you have this combination selected, you will also see Chat builds:

cannot be done right now, ultra-low priority to address this advanced case, if really you don't like this case, remove the build drivers section from this form until we have "per project" filters :)

**Comment by moul** [comment]
moved to #2
