### ISSUE TITLE
automatically detect platform type thanks to user agent

### ISSUE THREAD

**Issue by moul** [berty/yolo#138]

**Comment by ekelen** [comment]
Mozilla docs are scaring me away: https://developer.mozilla.org/en-US/docs/Web/HTTP/Browser_detection_using_the_user_agent

Is there a specific usage type you have in mind ?

**Comment by moul** [comment]
Something like this is enough: https://stackoverflow.com/questions/21741841/detecting-ios-android-operating-system

If you go on yolo.berty.io without any query string, then:

* If android: android builds only
* If iOS: iOS builds only
* Else: no filter ? I would like to give a try :)
