### ISSUE TITLE
Integrate Yolo + Berty logo for README and beyond

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#150]
Something like this, but good

<img width="578" alt="image" src="https://user-images.githubusercontent.com/24300177/80721010-ffba9b80-8afd-11ea-842b-c77d355eacac.png">

**Comment by moul** [comment]
@pierreboc, what's the current status for this one?

**Comment by pierreboc** [comment]
@moul my bad, I didn't pay attention that I was assigned to this issue. I will make a brief to Ombeline and come back to you asap

**Comment by pierreboc** [comment]
I just did a PR on assets.

**Comment by pierreboc** [comment]
![Yolo_by_Berty-01](https://user-images.githubusercontent.com/31745588/82467364-e041dd80-9ac1-11ea-9860-d1633ba7c340.png)

**Comment by moul** [comment]
@pierreboc can you put in on assets.berty.tech and provide the link?

then we will (you can also) update the README of yolo with the good image URL, and then we can close the issue

**Comment by pierreboc** [comment]
https://assets.berty.tech/v2-yolo_by_berty-01.png/
https://assets.berty.tech/v2-yolo_by_berty.svg/
