### ISSUE TITLE
Combine PRs with multiple builds into one card

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#156]
since a PR can have multiple builds, there are multiple strategies

1. to make as currently -> a block is a build, you can have multiple blocks for the same PR, it's kinda okay, but can become very confusing
2. if a build is from a merge request, then the block is for the merge request, and now there are two new options
  2.1. have another level of "sub-block" for each build, with older ones collapsed to only keep the most recent one visible
    ```
    PR 42
      BUILD 44
        ARTIFACT 44-1
        ARTIFACT 44-2
      BUILD 43 (collapsed)
      ...
    ```
  2.2. have something similar to a "feed" so basically you have will have something like this:
```
    PR 42
      BUILD 44 detail
      ARTIFACT 44-1
      ARTIFACT 44-2
      BUILD 43
      ARTIFACT 43-1
      ARTIFACT 43-2
      ...
```

_Originally posted by @moul in https://github.com/berty/yolo/issues/71#issuecomment-621310239_

**Comment by ekelen** [comment]
@moul Is there any way this can be done on the backend? 

Since the backend API has circular struct links (Build contains MR list, but MR is also linked to its builds), is there a way we can add a route/param to return the data with this inverted hierarchy? (e.g. have `merge_requests?mergerequest=shortid` or `/build-list?grouping=has_mergerequest`)

This can be done on the frontend but is kind of messy, since the styling of a 'build card' is tied directly to the expected hierarchy from the backend, so there would be many more conditions to handle if PRs with multiple builds are combined on the UI (and only in cases where there are multiple builds for a PR in the build list).

An agnostic 'card' element on the front is possible, but still much cleaner with a uniform structure coming from the back.

If that's not clear let me know and I will give more detail.

For now I am just going to keep one card == one build for the `build-list` route.

**Comment by moul** [comment]
Some builds don’t have linked PRs

Can you show me an example of how the API should look like ideally?

If needed I can give help for the front end algorithm with the current API

**Comment by ekelen** [comment]
For me algo is fine; I'm just going to attach an array of indices w/ matching PR ID to the first encounter of a build object with unique MR ID, and use those as a filter and map for what to pass to a buildcard.

API: For me the best would be to have the API take a parameter `group_by`/`display_group` that collects build objects under some matching key/value (e.g. `?group_by=has_mergerequest.driver` ---> all builds with same build driver would go in one "card"; result would look like:

```
  "JSON": {
    "display_group_path": "path.to.key" (e.g. 'has_mergerequest.author', else omit this),
    "builds": [
      {
        "value_of_grouping_key" (e.g. "Thomas"; else omit this level): [
           "id": "https://bintray.com/berty/gomobile-ipfs-demo/ios/0.0.70-test",
           "yolo_id": "b:GF5hTHX6Kxvv2M3X4VtWHozvj9yAWEdVvzHLNQ7yB4LK",
           "created_at": "2020-04-29T16:11:19.939Z",
           "updated_at": "2020-04-29T16:12:13.174Z",
           "state": "Passed",
....
```

Which would enable some easy filtering on the front ^^

**Comment by moul** [comment]
when grouping by mergerequest, how do you manage entries that does not have a mergerequest, are they still available in the API, what is the display_group_path and display_group_title in that case?

how do you plan to manage the sorting by date?
