### ISSUE TITLE
If the query has at least one "master" build, then, collapse all the non-master ones by default

### ISSUE THREAD

**Issue by moul** [berty/yolo#168]
![manfreds-imac - Screen Shot 2020-05-04 at 13 32 25](https://user-images.githubusercontent.com/94029/80961659-b2933e00-8e0b-11ea-8772-2cc39945f76e.png)

**Comment by moul** [comment]
also, you should add the title (or the first words of the PR title) in the bar itself, so it can be seen in the collapsed mode

**Comment by ekelen** [comment]
What kind of filter is this? `Build.ShortID`?

> also, you should add the title (or the first words of the PR title) in the bar itself, so it can be seen in the collapsed mode

Should have been added in #167
