### ISSUE TITLE
Always keep PR ID / Build ID even if mr title is present

### ISSUE THREAD

**Issue by moul** [berty/yolo#173]
From what I can see here https://github.com/berty/yolo/pull/167/files#diff-8f48c44535c68328f0c2048456477f14R61, as soon as a MR title is present, we completely lose the PR/build context, but we should just append the MR title instead of hiding everything else

Related with #167

**Comment by ekelen** [comment]
Makes sense. I will make one of them a subtitle (maybe the MR title), as it will get hard to read on small screen with everything as top level header

(Imagine this + long commit message):
![image](https://user-images.githubusercontent.com/24300177/80993941-36fdb500-8e3c-11ea-8006-c84aa14d81ad.png)
