### ISSUE TITLE
Make top-level build icon colors correspond with MR status

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#182]
Use github green/purple/red colours for top-level build icons with associated merge request.

Relates to #71

**Comment by ekelen** [comment]
1) The colors look unclear to me; the red looks like there is an error, and the 'Opened' green looks like some sort of success/resolution.

![image](https://user-images.githubusercontent.com/24300177/81295136-3d747280-9070-11ea-83fb-b4b7da2bc1e4.png)

![image](https://user-images.githubusercontent.com/24300177/81295422-aeb42580-9070-11ea-8691-4bb6a4f19f1f.png)

2) I'm not sure where to use the purple/"Merged" icon. From the API, I only have `Opened`, `Closed`, `UnknownState` as options for the `has_mergerequest.state`, (it looks like Closed (API) === Merged (Github) || Closed(Github) ?)

3) Proposal; to me it makes more sense to use the same icons as Github, but no color, so we have:

state === Closed or Merged:
![image](https://user-images.githubusercontent.com/24300177/81296429-2fbfec80-9072-11ea-8d1a-48a429df9b47.png)

state === Opened:
![image](https://user-images.githubusercontent.com/24300177/81297122-1d927e00-9073-11ea-9008-8b47a1cc7678.png)

----

For reference:

![image](https://user-images.githubusercontent.com/24300177/81295839-529dd100-9071-11ea-9c8b-a39b16a08465.png)

**Comment by ekelen** [comment]
@moul What do you think of this proposal in the preceding comment? (remove colors from card header icons if there is an attached merge request)

**Comment by moul** [comment]
I will add the merge state, and you will follow GitHub colors 

We won’t have much red, mostly purple for master and green for active PRs

And by the way, GitHub is  it using font color but bg color, I think that it will get better on our design, especially In dark mode, to have something with a background

**Comment by ekelen** [comment]
This was fixed (can't find the PR id, but we now have Master+MR+Merged -> GH purple, MR+Open -> GH green, other -> default text color, per below:

![image](https://user-images.githubusercontent.com/24300177/84087464-6e86f080-a9ea-11ea-8ece-35071f1ab53a.png)
