### ISSUE TITLE
Use human-friendly values in query params

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#185]
Even if there is a UI (eventually) for each query parameter, it would be cool if users can also use intuitive string values for possible query params.

e.g. Instead of `artifact_kinds=1` --> `artifact_kinds=IPA`
`build_driver=4` --> `build_driver=github`

**Comment by moul** [comment]
from what I can see, it should be already available: https://github.com/grpc-ecosystem/grpc-gateway/pull/314/files

I will check if I missed some configuration option

**Comment by ekelen** [comment]
kk. Here is an example, maybe I'm not formatting the request properly.

```
curl -u admin:xor+=cool "https://yolo.berty.io/api/build-list?artifact_kinds=APK"
{
  "code": 3,
  "message": "strconv.ParseInt: parsing \"APK\": invalid syntax"
}%
```

**Comment by moul** [comment]
moved to #2
