### ISSUE TITLE
Clicking on F5 ignores current query string

### ISSUE THREAD

**Issue by moul** [berty/yolo#186]
1. go https://yolo.berty.io/?mergerequest_author_id=https://github.com/n0izn0iz
2. click the `f5` input button
3. you'll be redirected here: https://yolo.berty.io/?artifact_kinds=1

---

bonus:

1. so, you're at step 3. and have been redirected
2. click on the "back" button of your browser
3. url will be changed to "https://yolo.berty.io/?mergerequest_author_id=https://github.com/n0izn0iz"
4. but the UI is not refreshed with new filters

**Comment by ekelen** [comment]
Currently doing :)
