### ISSUE TITLE
Return merged PR number in Build response with branch Master

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#192]
Currently there's no dedicated field for the merged MR ID number if branch is master. 

If branch is master, the only solution at the moment is to parse on front on `build.message` (Something like `Merge pull request #(\d+)`).

Alternatively, it would make sense to me to have a `build.has_mergerequest` for these builds;  (currently don't have if branch is master). We can then compare branch in has_mergerequest if we need to clarify the relationship between the master merge and the preceding merge request.

Relates to #191

**Comment by moul** [comment]
Can you double-check the API, I implemented this yesterday

**Comment by ekelen** [comment]
Okay yes, my bad, was looking at old postman request!
