### ISSUE TITLE
Return PR URL in API response for builds with branch Master

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#193]
Similar to #192 - builds with branch Master do not have associated merge requests in API response, so there is no URL directly available to create a link in buildcards.

Alternatively URL could be created in the front by parsing `build.message` for the PR ID and `has_project.driver + `has_project.id` for the URL.

Related to #191

**Comment by moul** [comment]
same as https://github.com/berty/yolo/issues/192#issuecomment-625193910

**Comment by ekelen** [comment]
Yep, it's implemented already, my mistake :)
