### ISSUE TITLE
Move inline React-CSS color styles to (s)css module file

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#256]
Get rid of all the `style={{ color: theme.text.sectionText }}` (for example) in our components. They are used almost everywhere and can replaced with a reference to one Sass module file.

The idea would be to import a global `.module.scss` file; declare `const { name } = useContext(themeContext)`, then replace `style={{...}}` with `className={...classNames, {...styles.light}}` (pseudo-code) to element attributes.

Caveat, not worth it if it doesn't visibly reduce component complexity.

**Comment by moul** [comment]
moved to #2
