### ISSUE TITLE
Make UI button/icon alignment and sizing consistent

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#257]
<img width="303" alt="image" src="https://user-images.githubusercontent.com/24300177/82201991-81ce0100-9901-11ea-9f92-fd3d5341df06.png">

<img width="949" alt="image" src="https://user-images.githubusercontent.com/24300177/82202098-b04bdc00-9901-11ea-824b-2d2c843d44ae.png">

- Chevron should be same size/alignment as gh and logs icons
- Download button should not be gargantuan
- Icons in tags should be either the same size or visibly smaller than other presentational icons

**Comment by moul** [comment]
moved to #2
