### ISSUE TITLE
Create clear grouping and/or visual hierarchy between build -> artifact

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#261]
Blocks with multiple builds (combined by MR) are hard to understand.

Probably need some combination of:

- Create visual hierarchy as in issue title (larger text/bold inside build info row, e.g.)
- Show 'n artifacts' tag/subtitle in build rows (followed by artifact list)
- Some separator/space between builds

**Comment by moul** [comment]
before improving the UI, start by minimizing all the non-last builds

![manfreds-imac - Screen Shot 2020-05-19 at 02 57 57](https://user-images.githubusercontent.com/94029/82273001-8be11580-997c-11ea-953f-46fae8dfdce5.png)

I see that you added a "hide artifact" button, remove it, and instead, add a "hide X previous builds"

in this screenshot, it will be just below the "iOS 1925" row and will contain all the builds + artifacts from "Build 686" row to "iOS 618" row
