### ISSUE TITLE
Add client-side build-list route

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#266]
It makes sense to add this as a fragment in the path; it is a specific view and doesn't call all 'homepage' use cases. Initially, root path `/` can immediately redirect to it.

**Comment by moul** [comment]
what other views do you have in mind?

**Comment by ekelen** [comment]
Came in here to close this (for now). The original idea is that 'home' might not always imply a build feed, but that is some ways off as this is currently the starting/only point for users of the app.
