### ISSUE TITLE
Use alternative logo/logo position for small screens

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#284]
Current logo is looking good on big screens (as long as you don't have too many filters selected):

![image](https://user-images.githubusercontent.com/24300177/82619932-86cbd280-9bd7-11ea-905c-b77e4ac3559b.png)

Gets weird on smaller screens:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/24300177/82619988-ac58dc00-9bd7-11ea-8116-241f9420bafc.png">

Related to #250

**Comment by moul** [comment]
moved to #2
