### ISSUE TITLE
Use vendor icons where possible in front

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#307]
e.g. buildkite, bintray, Berty Chat, etc. May split this into sub-issues if it ends up needing multiple passes.

**Comment by moul** [comment]
Is this issue still relevant, or can we close it?

**Comment by ekelen** [comment]
This was an old request; I think it would be very nice as the blocks are already cluttered with metadata, but it's not critical so your call.

**Comment by moul** [comment]
ok, closing for now :)
