### ISSUE TITLE
Always show the last master first

### ISSUE THREAD

**Issue by moul** [berty/yolo#328]
Default choice when choosing what to install is to choose the last master, so put it first :)

**Comment by ekelen** [comment]
This will not work too well with the date separators (and would be confusing if you are expecting to see builds in normal chronological order to find your test branch, etc). 

What do you think about either :
1) highlighting Master-branch BuildBlocks with a purple border (same colour as the purple master+merged icon)
2) adding `&branch=master` to default query search params? 

(The latter would also involve implementing the branch filter query on the front, but the UI is already there.)

**Comment by moul** [comment]
1 and 2 are not okay 

We need the last master first, nothing more to say about it 

Having active branches is very cool and should be available by default 

Just pick the first master, then use the original them including chronological, dates, etc, master is an exception

Another exception is « in progress builds » which should be just after master

Summary:

1. Most recent master if has at least one 
2. Active builds if there are some
3. Rest of the history including master, PRs, etc and date separators

**Comment by ekelen** [comment]
Hrrm, alright, we can do this, optimally (from my view) we can have separators that say what these sections are, followed by normal feeds, something like this with better wording

-- latest builds on master --
[...latest builds for projects in filters]

-- running builds (if they exist) --
[...running builds]

-- today --
.....
then normal date separators as they are now
....

**Comment by ekelen** [comment]
TODO:

- [ ] Remove latest master build from feed (or grey out)
- [ ] latest builds -> latest build
