### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by moul** [berty/yolo#345]
1. only keep the first build expanded, everything else should be collapsed by default (even merge on master)
2. merge on master should have more info in the title at the right of the merge number (tell me if you don't have the data in the API)
3. a collapsed line should be clickable entirely, and when mouse is over it should have a visual effect i.e., growing to suggest that there is an action at only one click
4. remove the "latest build on Master" line and the other line, instead, add a kind of flag "Latest" in the build itself, ideally I would love having a ribbon, but a badge is clearly okay

**Comment by ekelen** [comment]
for (2), you mean the same extra info as we have for non-master block titles (`has_mergerequest.title`), ja?

(fyi I think currently it's based on your suggestion for #191)

For (3), I assume you mean cases like this:

![image](https://user-images.githubusercontent.com/24300177/84787478-4c92fc80-afee-11ea-8728-edd0fb105813.png)

Do you mean you want the background of this block clickable anywhere (with the same action as clicking down-chevron icon), with the other little items with links in them (e.g. link to PR in title) still individually available?

**Comment by moul** [comment]
> for (2), you mean the same extra info as we have for non-master block titles (has_mergerequest.title), ja?

:+1: 

> For (3), I assume you mean cases like this:
> Do you mean you want the background of this block clickable anywhere (with the same action as clicking down-chevron icon), with the other little items with links in them (e.g. link to PR in title) still individually still functional?

:+1: :+1:

**Comment by ekelen** [comment]
For (1), are you referring to build blocks (aka cards), or builds within blocks? 

The latter is already the current behavior (within each build "block" there are multiple builds, grouped by MR; first build is always expanded (though only if it's master)).

**Comment by moul** [comment]
> For (1), are you referring to build blocks (aka cards), or builds within blocks?

yep, builds is okay, now I'm talking about the block (a "build group")
