### ISSUE TITLE
Improve UI<->HTTP Responses mapping

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#71]
To reconcile the mockup and the fields I get from server HTTP response, here are some fields I am missing or unclear about. Would be helpful for me and for others using the API to have them clarified.

![Screenshot 2020-04-17 at 12 40 37](https://user-images.githubusercontent.com/24300177/79573941-b01cae80-80bf-11ea-8ecb-05687f1a5f48.png)

1. ID in build title (circled in red)
2. ID next to Platform icon+name (circled in red)
3. Link that 'Logs' icon should point to
4. Link that Github logo shoudl point to
5. Icon to use in card header (Pull vs Merge icon next to build title; it's the green merge icon in screenshot)
6. Source of github user avatar
7. Author
8. Possible states for artifacts – is this complete/correct? Finished == Green, Yellow == Building, Pink == Failed
9. Date/time deltas in artifact list:
  * Calendar: (now - ?)
  * Clock: (now - ?)

🚧 More to come...

10. Possible states for builds – same question: Passed == Green, Pink == Failed, (Yellow?)
11. Platform to Kind mappings for Artifacts – IPA/DMG == Apple logo; APK == Android?

**Comment by ekelen** [comment]
For PRs with multiple builds, I think it makes most sense to sub-nest them (2.1), but for now I will keep BuildCards as BuildCards so I can implement the faster stuff sooner (made a separate issue for it)

**Comment by ekelen** [comment]
Just copypasting the list for sanity :)

- [X] 524 is not the PR number, but the build number
- [ ] a PR can have multiple builds
- [X] the PR ID is 1909 (.has_mergerequest.shortID)
- [X] you have a link to the commit on the icon on the left of the sha, but the sha is not a link -> it should be also be a link :)
- [X] on this icon and on the hash, if you keep the mouse hover, you should have the whole sha (not truncated)
- [X] on fields like "5 hours ago", mouse hover should print what is it "created" "finished" and the whole date, i.e. "created: 2020-04-29T13:13:05Z"
- [X] on duration fields (13 minutes), mouse hover should show duration: 12m59s
- [ ] the PR icon is purple, however this PR status is "opened" -> .has_mergerequest.state == "Opened"
- [ ] if the .has_mergerequest is available, you should use its title instead of the build one, in this PR, it should be: wip: fix: scenario test, waiting all members to know other's secrets
- [ ]  from what I can see, the "artifact" row in the design never have a description, maybe you can (for now) put the .has_artifacts.local_path, i.e.: js/packages/berty-app/android/universal.apk
- [ ] if the artifact has has_artifacts.file_size set, you can display the file size, it can be a good visual indicator that a specific build makes the result binary a lot more fat
- [ ] bintray with no relation to github --> since you don't have a PR or a project linked, the "build" details should be taken directly from the build info, i.e.; created_at, finished_at, etc
- [ ] also, we already have the project driver (GitHub), it's important to show the build driver (buildkite, bintray, circleci), if you don't have icon for now, just write the driver name

**Comment by moul** [comment]
![manfreds-imac - Screen Shot 2020-05-04 at 10 49 12](https://user-images.githubusercontent.com/94029/80949749-e6169e00-8df4-11ea-9749-80057bea1caf.png)

* "Passed" green button should link to the build logs
* "Finished" green button should link to the specific artifact build log (coming soon in the API)

**Comment by ekelen** [comment]
> bintray with no relation to github --> since you don't have a PR or a project linked, the "build" details should be taken directly from the build info, i.e.; created_at, finished_at, etc

What is the desired icon for this (top left of card)? Normally it's determined by `build.branch`.

**Comment by moul** [comment]
> @moul What is the desired icon for this (top left of card) in this scenario? Normally it's determined by build.branch.

a dedicated icon would be the best, else, you can consider that it's more like master than a PR, so reuse it

> What colour do we want for "Opened"? It's not too confusing to have Open+Pull be the same color as Master+Merged? (Yes they are different shapes.)

use same colors as github

![manfreds-imac - Screen Shot 2020-05-04 at 19 53 23](https://user-images.githubusercontent.com/94029/80996928-eb013f00-8e40-11ea-9b47-479c63ca6f2b.png)
![manfreds-imac - Screen Shot 2020-05-04 at 19 53 29](https://user-images.githubusercontent.com/94029/80996938-ed639900-8e40-11ea-84d6-72dfa067c64c.png)
![manfreds-imac - Screen Shot 2020-05-04 at 19 53 34](https://user-images.githubusercontent.com/94029/80996951-f2284d00-8e40-11ea-95b5-3dae3d7d994e.png)
![manfreds-imac - Screen Shot 2020-05-04 at 19 54 51](https://user-images.githubusercontent.com/94029/80997071-200d9180-8e41-11ea-81a9-91ff3a228860.png)

**Comment by ekelen** [comment]
I propose closing this; the incomplete items have their own issues (see checklist above).
