### ISSUE TITLE
Handle server requests for multiple artifact kinds

### ISSUE THREAD

**Issue by ekelen** [berty/yolo#75]
Currently the golang server only accepts requests for builds with artifacts from only one specified platform (iOS/'1' or android/'2') (or at least that is my understanding of `req *yolopb.BuildList_Request`; I'm tagging this issue as `question` for this reason).

Expected behavior: From the designs below, I'm assuming we want to also enable passing multiple platforms in parameters.

<img width="293" alt="image" src="https://user-images.githubusercontent.com/24300177/79773453-c5007880-8331-11ea-9a29-7ad8e8e09a1e.png">

<img width="331" alt="image" src="https://user-images.githubusercontent.com/24300177/79772968-14927480-8331-11ea-83c5-69b46d8394d0.png">

**Comment by moul** [comment]
just fyi, it's already managed from the API side :+1:

**Comment by ekelen** [comment]
Yes, the blocking part is on the frontend; comment: https://github.com/berty/yolo/issues/159#issuecomment-625212895
